# Generated by Django 6.0 on 2025-12-07 08:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['card_number'],
                'indexes': [models.Index(fields=['card_number'], name='core_card_card_nu_4023a2_idx'), models.Index(fields=['is_available'], name='core_card_is_avai_3fdb41_idx')],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('department', models.CharField(blank=True, max_length=100)),
                ('office_location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_preference', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('both', 'Both')], default='both', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secretary_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Secretaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending_otp', 'Pending OTP Verification'), ('pending_card', 'Pending Card Assignment'), ('pending_host_approval', 'Pending Host Approval'), ('approved', 'Approved - In Progress'), ('rejected', 'Rejected by Host'), ('finished', 'Finished by Host'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], db_index=True, default='pending_otp', max_length=30)),
                ('purpose', models.TextField(blank=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('host_approved_at', models.DateTimeField(blank=True, null=True)),
                ('host_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('host_finished_at', models.DateTimeField(blank=True, null=True)),
                ('secretary_card_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('secretary_card_collected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('host_instructions', models.TextField(blank=True)),
                ('check_in_method', models.CharField(choices=[('kiosk', 'Kiosk'), ('qr', 'QR Code')], default='kiosk', max_length=20)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='core.card')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.host')),
                ('secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='core.secretary')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='core.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('visitor_checkin', 'Visitor Check-in'), ('otp_generated', 'OTP Generated'), ('otp_verified', 'OTP Verified'), ('card_assigned', 'Card Assigned'), ('host_notified', 'Host Notified'), ('host_approved', 'Host Approved'), ('host_rejected', 'Host Rejected'), ('host_finished', 'Host Finished'), ('card_collected', 'Card Collected'), ('checkout', 'Check-out'), ('visit_cancelled', 'Visit Cancelled')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('blacklist_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='core_visito_phone_n_06202b_idx'), models.Index(fields=['created_at'], name='core_visito_created_568fc0_idx')],
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.visitor'),
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['phone_number'], name='core_host_phone_n_b19210_idx'),
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['is_active'], name='core_host_is_acti_b04a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['phone_number', 'is_verified'], name='core_otp_phone_n_3baad0_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['code', 'is_verified'], name='core_otp_code_62d978_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expires_at'], name='core_otp_expires_288351_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='core_auditl_user_id_413764_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['visit', 'created_at'], name='core_auditl_visit_i_4355a5_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status'], name='core_visit_status_8cac98_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['created_at'], name='core_visit_created_4d6338_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['check_in_time'], name='core_visit_check_i_7b6bd1_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visitor', 'status'], name='core_visit_visitor_53b67e_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['host', 'status'], name='core_visit_host_id_cffa6f_idx'),
        ),
    ]
