# Generated by Django 6.0 on 2025-12-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
