# Generated by Django 6.0 on 2025-12-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_visitor_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
